### PR TITLE
Expression evaluation functionality

### PR DESCRIPTION
**Pull request by gitting-around**
This is the latest version of the plugin that allows us to inject both inputs and outputs, provide expressions for the calculation of the values to be injected, as well provide expressions for when to inject an input/output. See the readme for how to write an ```events.xml``` file.

Methods for parsing ```events.xml``` are contained in Event.java.
The events are stored in an Event array, which is created when the wrapper is initialised.

In ```FaultInjectRuntimeModule.java```, the following methods can be found (among others):
* ```evaluateWhenCondition```: Checks whether an event should be applied at the current step. If an expression is provided including other inputs/outputs as variables, this is also taken into consideration here (this is not done for timestep equal to 0.0).
* ```getXXXFromEvent```: calls ```evaluateWhenCondition```, if an event should be injected at a given time, it calculates and returns the values that need to be injected.
* ```inject```: injects the new values instead of the correct ones, if any.

Currently there is no method for cleaning the array of events once any event becomes obsolete. This needs to be added. Since the code has changed substantially, the former cleaning method became obsolete.
I am using the ```testFuncEval()``` in the ```WaterTankSimpleTest```, which uses an alltypes.fmu, that has an input and output for each type. The xml file for this is ```funceval_when.xml```. 

More structured tests need to be added still.

### CODE REVIEW

**Comment by CThuleHansen** [comment]
Sorry, did not see this review request before now. Will check next week

**Comment by CThuleHansen** [comment]
Anything specific that you want me to look at?

**Comment by gitting-around** [comment]
No worries. I am more concerned with the efficiency of the methods. If you could have a look to the main methods I mentioned in the comment, from an optimisation perspective.

**Comment by CThuleHansen** [comment]
I think it is fine in general. All the dynamic evaluation stuff will take quite some time. So the things that can be created without the dynamic evaluation is best.

**Review by CThuleHansen — COMMENTED** [review]
See comments

**Pull request merged**
